MACRO(CERES_REPORT_NOT_FOUND REASON_MSG)
    SET(Ceres_FOUND FALSE)
    SET(CERES_FOUND FALSE)
    UNSET(CERES_INCLUDE_DIRS)
    UNSET(CERES_LIBRARIES)

    SET(CMAKE_MODULE_PATH ${CALLERS_CMAKE_MODULE_PATH})

    IF(Ceres_FIND_QUIETLY)
        MESSAGE(STATUS "Failed to find Ceres - "${REASON_MSG} ${ARGN})
    ELSE(Ceres_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Failed to find Ceres - "${REASON_MSG} ${ARGN})
    ELSE()
        MESSAGE(SEND_ERROR "Failed to find Ceres - "${REASON_MSG} ${ARGN})
    ENDIF()
    RETURN()
ENDMACRO(CERES_REPORT_NOT_FOUND)

GET_FILENAME_COMPONENT(CURRENT_CONFIG_INSTALL_DIR
    "${CMAKE_CURRENT_LIST_FILE}" PATH)

SET(CALLERS_CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH})

SET(CMAKE_MODULE_PATH  ${CURRENT_CONFIG_INSTALL_DIR)

GET_FILENAME_COMPONENT(CURRENT_ROOT_INSTALL_DIR
    ${CURRENT_CONFIG_INSTALL_DIR}/../../ ABSOLUTE)
IF(NOT EXISTS ${CURRENT_ROOT_INSTALL_DIR})
    CERES_REPORT_NOT_FOUND(
    "Ceres install root:${CURRENT_ROOT_INSTALL_DIR}, "
    "determined from relative path CeresConfig.cmake install location: "
    ""

)